### PR TITLE
Convert to EmberCLI 0.1.15 Addon

### PR DESCRIPTION
**Pull request by notmessenger**
This is an updated pull request with the desired spacing

### CODE REVIEW

**Comment by QuantumInformation** [comment]
Thanks! Really looking forward to working with this.

**Comment by QuantumInformation** [comment]
Testing the demo app, great job btw, works fine with my parse account!

**Comment by QuantumInformation** [comment]
@notmessenger would it be possible to add a logout button to the app and status based on whether the user is logged in? Currently if you refresh the UI is reset.

**Comment by notmessenger** [comment]
@QuantumInformation I recommend adding this as a new issue so that it can be specifically tracked as a desired item.  I do not know off the top of my head about the feasibility of the request but can look into it.

**Comment by QuantumInformation** [comment]
@notmessenger I noticed that you set a loggedIn variable in your test, however it seems that we can test for   `sessionToken  : DS.attr( 'string' )` Thats what I would like to use in my app.

**Pull request merged**
